---
# tasks file for aws_resources

 - name: Generate the Script to Run the Services
   template:
      src: "{{ item.sorc }}"
      dest: "{{ item.desti }}"
      mode: 0755
   register: repo_reg
   with_items:
    - {sorc: aws_resources.j2, desti: aws_scripts.sh}
    - {sorc: aws_configure.j2, desti: "~/.aws/config"}
 - debug:
      var: repo_reg.stdout_lines      

 - name: AWS Scripts for Resources List
   shell: "./aws_scripts.sh"
   register: te_status
 - debug:
      msg: "Scripts Execution"

 - name: Completed Successfully
   debug:
      msg: "Script Run Successfully"
